export const leadDispositionOptions = [
  "-None-",
  "Busy",
  "Closed",
  "Contact me Later.",
  "Contact me via Email",
  "Contact me via WhatsApp",
  "Customer Refused Contact",
  "CX'll inform the management",
  "Disconnected Number",
  "Do Not Call (DNC)",
  "Future Interest",
  "I Will Get Back To You",
  "Language Barrier",
  "No Answer",
  "Not a Business",
  "Not GCC number",
  "Not Interested",
  "Not Qualified",
  "Voicemail",
  "Will Visit You in the Office",
  "Wrong Number",
];
export const clickedAddOptions = [
  "-None-",
  "خدمة التسعير و الاستشارة المجانية",
  "سلامة الموقف الضريبي",
  "تقرير مفصل ابداء من دفتر مضبوط",
  "خلط الحسابات يخرب الربح",
  "مسك الدفاتر",
  "تخفيضات نهاية السنة على الادارة المحاسبية",
];
export const leadSourceOptions = [
  "-None-",
  "Direct Call",
  "Facebook",
  "Google",
  "Lead Files",
  "Partner",
  "Referral",
  "Website",
  "WhatsApp",
];
export const LeadStatusOptions = [
  "-None-",
  "Attempting to Contact",
  "Cold",
  "Contact Failed",
  "Future Interest",
  "Hot",
  "Interested",
  "Junk Lead",
  "Meeting Scheduled",
  "Not Interested",
  "Not Qualified",
  "Under Follow-Up",
];

export const AgentsOptions = ["Walid", "Farah", "Other"];
